<a href="https://colab.research.google.com/github/DanielSan33-4/ITA.Sprint08/blob/main/Sprint08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tasca S8.01. Analítica de dades en Pandas

## Nivell 1 - EDA estructurat i neteja bàsica

### Exercici 1: Exploració inicial del dataset

En aquest exercici has de realitzar una exploració inicial del DataFrame (sprint8_complex.xlsx) per respondre, com a mínim, a les següents preguntes:

- Quantes files i columnes té el dataset?
- Quin tipus de dades conté cada columna?
- Hi ha files duplicades?
- Les dades semblen coherents a primera vista?
- Detectes possibles problemes o inconsistències evidents?

Per fer-ho, hauràs de:

- Analitzar les dimensions del dataset
- Mostrar una mostra representativa de files
- Revisar els tipus de variables
- Les dades semblen coherents a primera vista?
- Detectar files duplicades
- Identificar i descriure possibles problemes inicials (sense solucionar-los encara)

In [1]:
import pandas as pd
from google.colab import drive
drive.mount("/content/drive")
ruta = "/content/drive/MyDrive/ITAcademy/sprint8_complex.xlsx"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
# Lectura del dataset
df_complex = pd.read_excel(ruta)
# Muestra representativa del mismo:
df_complex.head()

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7

Tras este primer vistazo podemos observar que el encabezado de la primera columna se encuentra en la primera fila y, en el resto de columnas, en la tercera. En esta primera columna, también encontramos como envcabezado el nombre de la tabla.

También se observan algunos NA's y acentos mal tipificados o caracteres que no encajan con lo que se esperaría.

In [4]:
# Quantes files i columnes té el dataset?
print(f'El dataset tiene {df_complex.shape} filas y columnas.')

El dataset tiene (1010, 20) filas y columnas.

In [6]:
# Quin tipus de dades conté cada columna?
print(f' El tipo de cada columna es el siguiente: \n{df_complex.dtypes}')

Dades de l'enquesta de treballadors 2025    object
Unnamed: 1                                  object
Unnamed: 2                                  object
Unnamed: 3                                  object
Unnamed: 4                                  object
Unnamed: 5                                  object
Unnamed: 6                                  object
Unnamed: 7                                  object
Unnamed: 8                                  object
Unnamed: 9                                  object
Unnamed: 10                                 object
Unnamed: 11                                 object
Unnamed: 12                                 object
Unnamed: 13                                 object
Unnamed: 14                                 object
Unnamed: 15                                 object
Unnamed: 16                                 object
Unnamed: 17                                 object
Unnamed: 18                                 object
Unnamed: 19                                 object
dtype: object

No se puede sacar ninguna conclusion del tipo de cada columna, ya que al no estar los encabezados mezclados con los datos, el programa no puede detectar automáticamente el tipo de dato que tenemos por columna. Sería necesario volver a comprobar el `dtypes` una vez limpiado el dataframe.